jpa:
  hibernate:
    ddl-auto: create
  properties:
    hibernate:
      format_sql: true
logging:
  level:
    feign:
      Client: DEBUG
      Logger: DEBUG
    org:
      hibernate:
        SQL: debug
server:
  port: 8084
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-response: true
servlet:
  servlet:
    register-default-servlet: true
spring:
  doc:
    api-docs:
      path: /v3/api-docs
      enabled: true
    swagger-ui:
      enabled: true
      path: /swagger-ui.html
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@gsdb1_high?TNS_ADMIN=./src/main/resources/wallet
    username: ADMIN
    password: '@dminPassword1234!'
  hikari:
    connection-timeout: 100000
    validation-timeout: 100000
    idle-timeout: 100000
    max-lifetime: 420000
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_Sql_comments: true
  cloud:
    discovery:
      client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/
  main:
    allow-bean-definition-overriding: true
feign:
  client:
    config:
      log-client:
        loggerLevel: FULL
        retryer:
          maxAttempts: 5
          backoff:
            period: 1000
            maxPeriod: 5000
    CoinOneClient:
      url: https://api.coinone.co.kr/public/v2
    CoreClient:
      url: http://localhost:8082/api/comm