jpa:
  hibernate:
    ddl-auto: create
  properties:
    hibernate:
      format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
server:
  port: 8085
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-response: true
servlet:
  servlet:
    register-default-servlet: true
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@gsdb1_high?TNS_ADMIN=./src/main/resources/wallet
    username: ADMIN
    password: '@dminPassword1234!'
  hikari:
    connection-timeout: 100000
    validation-timeout: 100000
    idle-timeout: 100000
    max-lifetime: 420000
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_Sql_comments: true
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  thymeleaf:
    prefix: classpath:/static/
feign:
  client:
    config:
      log-client:
        loggerLevel: FULL
        retryer:
          maxAttempts: 5
          backoff:
            period: 1000
            maxPeriod: 5000
    CoreClient:
      url: http://localhost:8082/api/comm
    StockClient:
      url: http://localhost:8083/api/stock
    CoinClient:
      url: http://localhost:8084/api/coin
